const universalData = {
    mcu: {
        title: "Marvel Cinematic Universe",
        themeColor: "red",
        data: [
            { category: "Phase 1", title: "Iron Man", year: 2008, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 1", title: "The Incredible Hulk", year: 2008, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 1", title: "Iron Man 2", year: 2010, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 1", title: "Thor", year: 2011, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 1", title: "Captain America: The First Avenger", year: 2011, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 1", title: "The Avengers", year: 2012, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Iron Man 3", year: 2013, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Agents of S.H.I.E.L.D.", year: "2013-2020", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 2", title: "Thor: The Dark World", year: 2013, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Captain America: The Winter Soldier", year: 2014, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Guardians of the Galaxy", year: 2014, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Agent Carter", year: "2015-2016", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 2", title: "Daredevil", year: "2015-2018", type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Avengers: Age of Ultron", year: 2015, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Ant-Man", year: 2015, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 2", title: "Jessica Jones", year: "2015-2019", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Captain America: Civil War", year: 2016, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Luke Cage", year: "2016-2018", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Doctor Strange", year: 2016, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Iron Fist", year: "2017-2018", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Guardians of the Galaxy Vol. 2", year: 2017, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Spider-Man: Homecoming", year: 2017, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "The Defenders", year: 2017, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Inhumans", year: 2017, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Thor: Ragnarok", year: 2017, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "The Punisher", year: "2017-2019", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Runaways", year: "2017-2019", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Black Panther", year: 2018, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Avengers: Infinity War", year: 2018, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Cloak & Dagger", year: "2018-2019", type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 3", title: "Ant-Man and the Wasp", year: 2018, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Captain Marvel", year: 2019, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Avengers: Endgame", year: 2019, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 3", title: "Spider-Man: Far From Home", year: 2019, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "WandaVision", year: 2021, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "The Falcon and the Winter Soldier", year: 2021, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Loki: Season 1", year: 2021, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Black Widow", year: 2021, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "What If...?: Season 1", year: 2021, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 4", title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Eternals", year: 2021, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Hawkeye", year: 2021, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Spider-Man: No Way Home", year: 2021, type: "Movie", hotstar: "No", hindi: "N/A" },
            { category: "Phase 4", title: "Moon Knight", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Doctor Strange in the Multiverse of Madness", year: 2022, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Ms. Marvel", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Thor: Love and Thunder", year: 2022, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "I Am Groot", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "She-Hulk: Attorney at Law", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Werewolf by Night", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "Black Panther: Wakanda Forever", year: 2022, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 4", title: "The Guardians of the Galaxy Holiday Special", year: 2022, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Ant-Man and the Wasp: Quantumania", year: 2023, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Guardians of the Galaxy Vol. 3", year: 2023, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Secret Invasion", year: 2023, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Loki: Season 2", year: 2023, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "The Marvels", year: 2023, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "What If...?: Season 2", year: 2023, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 5", title: "Echo", year: 2024, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Agatha All Along", year: 2024, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "What If...?: Season 3", year: 2024, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 5", title: "Your Friendly Neighborhood Spider-Man", year: 2025, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Captain America: Brave New World", year: 2025, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Daredevil: Born Again", year: 2025, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Thunderbolts*", year: 2025, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 5", title: "Ironheart", year: 2025, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 6", title: "The Fantastic Four: First Steps", year: 2025, type: "Movie", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 6", title: "Eyes of Wakanda", year: 2025, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 6", title: "Marvel Zombies", year: 2025, type: "TV Show", hotstar: "Yes", hindi: "No" },
            { category: "Phase 6", title: "Wonder Man", year: 2026, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
            { category: "Phase 6", title: "Daredevil: Born Again: Season 2", year: 2026, type: "TV Show", hotstar: "Yes", hindi: "Yes" },
        ]
    },
    dc: {
        title: "DC Universe",
        themeColor: "blue",
        data: [
            { category: "DCEU Movies", title: "Man of Steel", year: 2013, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Batman v Superman: Dawn of Justice", year: 2016, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Suicide Squad", year: 2016, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Wonder Woman", year: 2017, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Justice League", year: 2017, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Aquaman", year: 2018, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Shazam!", year: 2019, ott: "Netflix", hindi: "Yes" },
            { category: "DCEU Movies", title: "Birds of Prey", year: 2020, ott: "Netflix", hindi: "Yes" },
            { category: "DCEU Movies", title: "Wonder Woman 1984", year: 2020, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Zack Snyder's Justice League", year: 2021, ott: "JioCinema", hindi: "Yes" },
            { category: "DCEU Movies", title: "The Suicide Squad", year: 2021, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Black Adam", year: 2022, ott: "Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "Shazam! Fury of the Gods", year: 2023, ott: "JioCinema / Prime Video", hindi: "Yes" },
            { category: "DCEU Movies", title: "The Flash", year: 2023, ott: "JioCinema", hindi: "Yes" },
            { category: "DCEU Movies", title: "Blue Beetle", year: 2023, ott: "JioCinema", hindi: "Yes" },
            { category: "DCEU Movies", title: "Aquaman and the Lost Kingdom", year: 2023, ott: "JioCinema", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 1", year: "2012-13", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 2", year: "2013-14", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 1", year: "2014-15", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 3", year: "2014-15", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 2", year: "2015-16", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 4", year: "2015-16", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Supergirl: Season 1", year: "2015-16", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Legends of Tomorrow: Season 1", year: 2016, ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 3", year: "2016-17", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 5", year: "2016-17", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Supergirl: Season 2", year: "2016-17", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Legends of Tomorrow: Season 2", year: "2016-17", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 4", year: "2017-18", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 6", year: "2017-18", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Supergirl: Season 3", year: "2017-18", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Legends of Tomorrow: Season 3", year: "2017-18", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Black Lightning: Season 1", year: 2018, ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 5", year: "2018-19", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 7", year: "2018-19", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Supergirl: Season 4", year: "2018-19", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Legends of Tomorrow: Season 4", year: "2018-19", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Black Lightning: Season 2", year: "2018-19", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Batwoman: Season 1", year: "2019-20", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "The Flash: Season 6", year: "2019-20", ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Arrow: Season 8", year: "2019-20", ott: "Netflix", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Supergirl: Season 5", year: "2019-20", ott: "Prime Video", hindi: "No" },
            { category: "Arrowverse TV Shows", title: "Legends of Tomorrow: Season 5", year: 2020, ott: "Prime Video", hindi: "Yes" },
            { category: "Arrowverse TV Shows", title: "Black Lightning: Season 3", year: "2019-20", ott: "Netflix", hindi: "No" },
        ]
    },
    xmen: {
        title: "X-Men Universe",
        themeColor: "yellow",
        data: [
            { category: "X-Men Original Trilogy", title: "X-Men", year: 2000, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Original Trilogy", title: "X2: X-Men United", year: 2003, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Original Trilogy", title: "X-Men: The Last Stand", year: 2006, hotstar: "Yes", hindi: "Yes" },
            { category: "Wolverine Trilogy", title: "X-Men Origins: Wolverine", year: 2009, hotstar: "Yes", hindi: "Yes" },
            { category: "Wolverine Trilogy", title: "The Wolverine", year: 2013, hotstar: "Yes", hindi: "Yes" },
            { category: "Wolverine Trilogy", title: "Logan", year: 2017, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Prequel Films", title: "X-Men: First Class", year: 2011, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Prequel Films", title: "X-Men: Days of Future Past", year: 2014, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Prequel Films", title: "X-Men: Apocalypse", year: 2016, hotstar: "Yes", hindi: "Yes" },
            { category: "X-Men Prequel Films", title: "Dark Phoenix", year: 2019, hotstar: "Yes", hindi: "Yes" },
            { category: "Deadpool Films", title: "Deadpool", year: 2016, hotstar: "Yes", hindi: "Yes" },
            { category: "Deadpool Films", title: "Deadpool 2", year: 2018, hotstar: "Yes", hindi: "Yes" },
            { category: "Deadpool Films", title: "Deadpool & Wolverine", year: 2024, hotstar: "Yes", hindi: "Yes" },
            { category: "Spin-off", title: "The New Mutants", year: 2020, hotstar: "Yes", hindi: "Yes" },
        ]
    }
};
